import type { Recipe } from "./types";

// V1 mock recipe DB. The selection engine in meal-planner.ts filters and ranks these
// using the user's profile + daily context. Designed to be replaced by a server-side
// AI call (see meal-planner.ts) without changing consumers.
export const RECIPES: Recipe[] = [
  // ───────── Breakfasts ─────────
  {
    id: "b1",
    name: "Apple & Walnut Overnight Oats",
    mealType: "breakfast",
    imagePrompt: "overnight oats in a glass jar with apple and walnuts, soft morning light",
    prepMinutes: 5,
    effort: "nobrain",
    budget: "low",
    tags: ["vegetarian"],
    contains: ["oats", "apple", "walnut", "yogurt", "milk"],
    ingredients: [
      { name: "Rolled oats", qtyPerServing: "50 g", category: "grains" },
      { name: "Plant or dairy milk", qtyPerServing: "180 ml", category: "dairy" },
      { name: "Greek yogurt", qtyPerServing: "60 g", category: "dairy" },
      { name: "Apple", qtyPerServing: "½", category: "produce" },
      { name: "Walnuts", qtyPerServing: "15 g", category: "pantry" },
      { name: "Cinnamon", qtyPerServing: "pinch", category: "pantry" },
    ],
    steps: [
      "Mix oats, milk and yogurt in a jar. Stir well.",
      "Top with grated apple, walnuts and cinnamon.",
      "Refrigerate overnight, or eat after 10 minutes for a softer texture.",
    ],
    calories: 380, protein: 14, carbs: 52, fats: 12,
    portions: { protein: "1 thumb of yogurt", carbs: "1 fist of oats", veg: "½ apple", fats: "1 thumb of nuts" },
    warmth: "neutral", carbDensity: "medium", style: "clean",
  },
  {
    id: "b2",
    name: "Soft Scramble on Sourdough",
    mealType: "breakfast",
    imagePrompt: "soft buttery scrambled eggs on toasted sourdough with chives",
    prepMinutes: 10,
    effort: "simple",
    budget: "low",
    tags: ["vegetarian"],
    contains: ["egg", "butter", "bread", "sourdough"],
    ingredients: [
      { name: "Eggs", qtyPerServing: "2", category: "protein" },
      { name: "Butter", qtyPerServing: "10 g", category: "dairy" },
      { name: "Sourdough", qtyPerServing: "1 slice", category: "grains" },
      { name: "Chives", qtyPerServing: "to taste", category: "produce" },
    ],
    steps: [
      "Whisk eggs with a pinch of salt.",
      "Melt butter in a non-stick pan over low heat, add eggs and stir slowly.",
      "Remove while still glossy. Pile onto toasted sourdough, top with chives.",
    ],
    calories: 420, protein: 22, carbs: 28, fats: 24,
    portions: { protein: "1 palm of eggs", carbs: "1 fist of bread", veg: "small handful herbs", fats: "1 thumb of butter" },
    warmth: "warm", carbDensity: "medium", style: "comfort",
  },
  {
    id: "b3",
    name: "Berry Protein Smoothie",
    mealType: "breakfast",
    imagePrompt: "purple berry smoothie in a tall glass with chia seeds on top",
    prepMinutes: 5,
    effort: "nobrain",
    budget: "medium",
    tags: ["vegetarian", "gluten-free"],
    contains: ["berries", "banana", "yogurt", "milk", "chia"],
    ingredients: [
      { name: "Frozen berries", qtyPerServing: "120 g", category: "produce" },
      { name: "Banana", qtyPerServing: "½", category: "produce" },
      { name: "Greek yogurt", qtyPerServing: "150 g", category: "dairy" },
      { name: "Milk of choice", qtyPerServing: "150 ml", category: "dairy" },
      { name: "Chia seeds", qtyPerServing: "1 tsp", category: "pantry" },
    ],
    steps: [
      "Blend everything until smooth and creamy.",
      "Pour into a glass, top with a few extra berries.",
    ],
    calories: 320, protein: 24, carbs: 38, fats: 7,
    portions: { protein: "1 palm of yogurt", carbs: "1 fist of fruit", veg: "—", fats: "1 thumb of seeds" },
    warmth: "cool", carbDensity: "medium", style: "clean",
  },
  {
    id: "b4",
    name: "Savoury Spinach & Feta Omelette",
    mealType: "breakfast",
    imagePrompt: "fluffy omelette folded over spinach and feta on a ceramic plate",
    prepMinutes: 10,
    effort: "simple",
    budget: "low",
    tags: ["vegetarian", "gluten-free"],
    contains: ["egg", "spinach", "feta", "dairy"],
    ingredients: [
      { name: "Eggs", qtyPerServing: "3", category: "protein" },
      { name: "Spinach", qtyPerServing: "large handful", category: "produce" },
      { name: "Feta", qtyPerServing: "30 g", category: "dairy" },
      { name: "Olive oil", qtyPerServing: "1 tsp", category: "pantry" },
    ],
    steps: [
      "Wilt spinach in a hot oiled pan, set aside.",
      "Pour beaten eggs into the pan, swirl, and let set on low heat.",
      "Top with spinach and feta, fold and slide onto a plate.",
    ],
    calories: 380, protein: 28, carbs: 4, fats: 28,
    portions: { protein: "1.5 palms of eggs", carbs: "—", veg: "2 handfuls spinach", fats: "1 thumb feta" },
    warmth: "warm", carbDensity: "low", style: "balanced",
  },
  {
    id: "b5",
    name: "Banana Nut Porridge",
    mealType: "breakfast",
    imagePrompt: "warm porridge bowl topped with banana slices, almonds and honey",
    prepMinutes: 12,
    effort: "simple",
    budget: "low",
    tags: ["vegetarian"],
    contains: ["oats", "banana", "almond", "milk"],
    ingredients: [
      { name: "Rolled oats", qtyPerServing: "60 g", category: "grains" },
      { name: "Milk of choice", qtyPerServing: "250 ml", category: "dairy" },
      { name: "Banana", qtyPerServing: "1", category: "produce" },
      { name: "Almonds", qtyPerServing: "15 g", category: "pantry" },
      { name: "Honey or maple", qtyPerServing: "1 tsp", category: "pantry" },
    ],
    steps: [
      "Simmer oats with milk on low for 5–7 minutes until creamy.",
      "Pour into a bowl and top with sliced banana, almonds and a drizzle of honey.",
    ],
    calories: 460, protein: 14, carbs: 72, fats: 14,
    portions: { protein: "1 thumb of nuts", carbs: "1.5 fists of oats", veg: "—", fats: "1 thumb of nuts" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },

  // ───────── Lunches ─────────
  {
    id: "l1",
    name: "Lemon Tahini Grain Bowl",
    mealType: "lunch",
    imagePrompt: "vibrant grain bowl with quinoa, roasted chickpeas, greens and lemon tahini",
    prepMinutes: 20,
    effort: "simple",
    budget: "medium",
    tags: ["vegetarian", "vegan", "nut-free"],
    contains: ["quinoa", "chickpeas", "tahini", "greens", "lemon"],
    ingredients: [
      { name: "Quinoa", qtyPerServing: "70 g dry", category: "grains" },
      { name: "Chickpeas (cooked)", qtyPerServing: "150 g", category: "protein" },
      { name: "Mixed greens", qtyPerServing: "2 handfuls", category: "produce" },
      { name: "Tahini", qtyPerServing: "1 tbsp", category: "pantry" },
      { name: "Lemon", qtyPerServing: "½", category: "produce" },
      { name: "Olive oil", qtyPerServing: "1 tsp", category: "pantry" },
    ],
    steps: [
      "Cook quinoa in salted water until fluffy. Drain.",
      "Roast chickpeas with olive oil for 12 min at 220°C until crisp.",
      "Whisk tahini with lemon juice and warm water to a pourable sauce.",
      "Build the bowl, drizzle with sauce.",
    ],
    calories: 540, protein: 22, carbs: 70, fats: 18,
    portions: { protein: "1 palm chickpeas", carbs: "1 fist quinoa", veg: "2 handfuls greens", fats: "1 thumb tahini" },
    warmth: "cool", carbDensity: "high", style: "clean",
  },
  {
    id: "l2",
    name: "Chicken & Avocado Wrap",
    mealType: "lunch",
    imagePrompt: "chicken wrap with avocado and lettuce cut in half on a wooden board",
    prepMinutes: 15,
    effort: "simple",
    budget: "medium",
    tags: [],
    contains: ["chicken", "avocado", "wrap", "tortilla", "yogurt"],
    ingredients: [
      { name: "Chicken breast", qtyPerServing: "120 g", category: "protein" },
      { name: "Wholewheat wrap", qtyPerServing: "1", category: "grains" },
      { name: "Avocado", qtyPerServing: "½", category: "produce" },
      { name: "Lettuce", qtyPerServing: "small handful", category: "produce" },
      { name: "Greek yogurt", qtyPerServing: "2 tbsp", category: "dairy" },
    ],
    steps: [
      "Sear seasoned chicken 4 min per side, rest, then slice.",
      "Spread yogurt across the wrap, layer lettuce, avocado, chicken.",
      "Roll tightly and slice in half.",
    ],
    calories: 520, protein: 38, carbs: 38, fats: 22,
    portions: { protein: "1 palm chicken", carbs: "1 fist wrap", veg: "1 handful lettuce", fats: "1 thumb avocado" },
    warmth: "neutral", carbDensity: "medium", style: "balanced",
  },
  {
    id: "l3",
    name: "Miso Salmon Rice Bowl",
    mealType: "lunch",
    imagePrompt: "glossy miso glazed salmon over rice with bok choy",
    prepMinutes: 25,
    effort: "proper",
    budget: "high",
    tags: ["pescatarian", "nut-free"],
    contains: ["salmon", "rice", "miso", "ginger", "bok choy"],
    ingredients: [
      { name: "Salmon fillet", qtyPerServing: "140 g", category: "protein" },
      { name: "Jasmine rice", qtyPerServing: "70 g dry", category: "grains" },
      { name: "Bok choy", qtyPerServing: "2 small heads", category: "produce" },
      { name: "White miso", qtyPerServing: "1 tbsp", category: "pantry" },
      { name: "Ginger", qtyPerServing: "thumb", category: "produce" },
    ],
    steps: [
      "Brush salmon with miso + grated ginger, bake at 200°C for 10 min.",
      "Cook rice. Steam bok choy until just tender.",
      "Plate rice, top with salmon and greens, spoon over pan juices.",
    ],
    calories: 620, protein: 40, carbs: 68, fats: 18,
    portions: { protein: "1 palm salmon", carbs: "1 fist rice", veg: "2 handfuls bok choy", fats: "1 thumb oils" },
    warmth: "warm", carbDensity: "high", style: "balanced",
  },
  {
    id: "l4",
    name: "10-Minute Tuna Bean Salad",
    mealType: "lunch",
    imagePrompt: "rustic tuna and white bean salad with parsley and lemon",
    prepMinutes: 10,
    effort: "nobrain",
    budget: "low",
    tags: ["pescatarian", "gluten-free", "nut-free"],
    contains: ["tuna", "beans", "lemon", "parsley", "olive"],
    ingredients: [
      { name: "Canned tuna", qtyPerServing: "1 tin (100 g)", category: "protein" },
      { name: "White beans (canned)", qtyPerServing: "150 g", category: "pantry" },
      { name: "Parsley", qtyPerServing: "small handful", category: "produce" },
      { name: "Lemon", qtyPerServing: "½", category: "produce" },
      { name: "Olive oil", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: [
      "Rinse beans, drain tuna.",
      "Toss everything with lemon juice, olive oil, salt and pepper.",
    ],
    calories: 420, protein: 34, carbs: 32, fats: 16,
    portions: { protein: "1 palm tuna", carbs: "1 fist beans", veg: "small handful herbs", fats: "1 thumb olive oil" },
    warmth: "cool", carbDensity: "medium", style: "clean",
  },
  {
    id: "l5",
    name: "Roasted Roots & Tahini Bowl",
    mealType: "lunch",
    imagePrompt: "roasted sweet potato and carrots over couscous with tahini and parsley",
    prepMinutes: 30,
    effort: "proper",
    budget: "low",
    tags: ["vegetarian", "vegan"],
    contains: ["sweet potato", "carrot", "couscous", "tahini", "chickpeas"],
    ingredients: [
      { name: "Sweet potato", qtyPerServing: "200 g", category: "produce" },
      { name: "Carrots", qtyPerServing: "2", category: "produce" },
      { name: "Couscous", qtyPerServing: "60 g dry", category: "grains" },
      { name: "Chickpeas", qtyPerServing: "100 g", category: "protein" },
      { name: "Tahini", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: [
      "Roast cubed roots and chickpeas with oil and cumin at 220°C for 25 min.",
      "Soak couscous in hot water for 5 min, fluff with a fork.",
      "Build the bowl and drizzle with thinned tahini.",
    ],
    calories: 560, protein: 18, carbs: 88, fats: 14,
    portions: { protein: "1 palm chickpeas", carbs: "1.5 fists roots+couscous", veg: "2 handfuls", fats: "1 thumb tahini" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },

  // ───────── Dinners ─────────
  {
    id: "d1",
    name: "Lemon Garlic Chicken & Greens",
    mealType: "dinner",
    imagePrompt: "pan seared chicken with lemon and sautéed greens on a ceramic plate",
    prepMinutes: 25,
    effort: "simple",
    budget: "medium",
    tags: ["gluten-free", "nut-free"],
    contains: ["chicken", "lemon", "garlic", "greens", "olive"],
    ingredients: [
      { name: "Chicken thighs", qtyPerServing: "180 g", category: "protein" },
      { name: "Garlic", qtyPerServing: "2 cloves", category: "produce" },
      { name: "Lemon", qtyPerServing: "½", category: "produce" },
      { name: "Greens (kale or chard)", qtyPerServing: "2 handfuls", category: "produce" },
      { name: "Olive oil", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: [
      "Sear chicken skin-side down for 6 min, flip, finish 5 min more.",
      "Remove chicken, sauté garlic and greens in the same pan.",
      "Return chicken, squeeze lemon over and serve.",
    ],
    calories: 480, protein: 42, carbs: 8, fats: 28,
    portions: { protein: "1.5 palms chicken", carbs: "—", veg: "2 handfuls greens", fats: "1 thumb olive oil" },
    warmth: "warm", carbDensity: "low", style: "balanced",
  },
  {
    id: "d2",
    name: "Roasted Tomato Recovery Pasta",
    mealType: "dinner",
    imagePrompt: "rustic pasta with slow roasted tomatoes, basil and parmesan",
    prepMinutes: 30,
    effort: "simple",
    budget: "low",
    tags: ["vegetarian"],
    contains: ["pasta", "tomato", "basil", "parmesan", "garlic"],
    ingredients: [
      { name: "Pasta", qtyPerServing: "100 g dry", category: "grains" },
      { name: "Cherry tomatoes", qtyPerServing: "250 g", category: "produce" },
      { name: "Garlic", qtyPerServing: "3 cloves", category: "produce" },
      { name: "Basil", qtyPerServing: "small handful", category: "produce" },
      { name: "Parmesan", qtyPerServing: "20 g", category: "dairy" },
      { name: "Olive oil", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: [
      "Roast tomatoes with garlic and oil at 200°C for 20 min.",
      "Cook pasta to al dente, keep a splash of water.",
      "Toss everything together, finish with basil and parmesan.",
    ],
    calories: 580, protein: 20, carbs: 92, fats: 14,
    portions: { protein: "1 thumb parmesan", carbs: "1.5 fists pasta", veg: "1 handful tomatoes", fats: "1 thumb oil" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },
  {
    id: "d3",
    name: "Chickpea Coconut Curry",
    mealType: "dinner",
    imagePrompt: "creamy chickpea curry with coconut milk and coriander over rice",
    prepMinutes: 25,
    effort: "simple",
    budget: "low",
    tags: ["vegetarian", "vegan", "gluten-free"],
    contains: ["chickpeas", "coconut", "tomato", "rice", "curry"],
    ingredients: [
      { name: "Chickpeas (cooked)", qtyPerServing: "180 g", category: "protein" },
      { name: "Coconut milk", qtyPerServing: "150 ml", category: "pantry" },
      { name: "Tinned tomatoes", qtyPerServing: "150 g", category: "pantry" },
      { name: "Onion", qtyPerServing: "½", category: "produce" },
      { name: "Curry powder", qtyPerServing: "1 tbsp", category: "pantry" },
      { name: "Rice", qtyPerServing: "70 g dry", category: "grains" },
    ],
    steps: [
      "Soften onion in oil, add curry powder and bloom 30 s.",
      "Add tomatoes and coconut milk, simmer 5 min.",
      "Stir in chickpeas, simmer 10 min. Serve with rice.",
    ],
    calories: 600, protein: 20, carbs: 82, fats: 20,
    portions: { protein: "1 palm chickpeas", carbs: "1 fist rice", veg: "1 handful onion+tomato", fats: "1 thumb coconut" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },
  {
    id: "d4",
    name: "Sheet-Pan Salmon & Greens",
    mealType: "dinner",
    imagePrompt: "sheet pan salmon with broccoli and lemon slices",
    prepMinutes: 20,
    effort: "simple",
    budget: "high",
    tags: ["pescatarian", "gluten-free", "nut-free"],
    contains: ["salmon", "broccoli", "lemon", "olive"],
    ingredients: [
      { name: "Salmon fillet", qtyPerServing: "150 g", category: "protein" },
      { name: "Broccoli", qtyPerServing: "200 g", category: "produce" },
      { name: "Lemon", qtyPerServing: "½", category: "produce" },
      { name: "Olive oil", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: [
      "Toss broccoli with oil, roast at 220°C for 8 min.",
      "Push aside, lay salmon on the tray, roast 10 min more.",
      "Squeeze lemon over to finish.",
    ],
    calories: 460, protein: 38, carbs: 14, fats: 28,
    portions: { protein: "1 palm salmon", carbs: "—", veg: "2 handfuls broccoli", fats: "1 thumb olive oil" },
    warmth: "warm", carbDensity: "low", style: "clean",
  },
  {
    id: "d5",
    name: "Quick Stir-Fry Beef & Veg",
    mealType: "dinner",
    imagePrompt: "wok stir fry of beef strips with peppers and noodles",
    prepMinutes: 15,
    effort: "simple",
    budget: "medium",
    tags: [],
    contains: ["beef", "pepper", "noodle", "soy", "ginger"],
    ingredients: [
      { name: "Beef strips", qtyPerServing: "140 g", category: "protein" },
      { name: "Peppers", qtyPerServing: "1", category: "produce" },
      { name: "Egg noodles", qtyPerServing: "80 g dry", category: "grains" },
      { name: "Soy sauce", qtyPerServing: "1 tbsp", category: "pantry" },
      { name: "Ginger", qtyPerServing: "thumb", category: "produce" },
    ],
    steps: [
      "Cook noodles, drain.",
      "Sear beef in a hot wok 2 min, add peppers and ginger, toss 2 min.",
      "Add noodles and soy, toss to coat and serve.",
    ],
    calories: 560, protein: 38, carbs: 60, fats: 18,
    portions: { protein: "1 palm beef", carbs: "1 fist noodles", veg: "1 handful peppers", fats: "1 thumb oil" },
    warmth: "warm", carbDensity: "high", style: "balanced",
  },
  {
    id: "d6",
    name: "Lentil Soup with Cumin & Lemon",
    mealType: "dinner",
    imagePrompt: "warm red lentil soup with a swirl of olive oil and lemon",
    prepMinutes: 30,
    effort: "simple",
    budget: "low",
    tags: ["vegetarian", "vegan", "gluten-free"],
    contains: ["lentil", "carrot", "onion", "cumin", "lemon"],
    ingredients: [
      { name: "Red lentils", qtyPerServing: "80 g dry", category: "pantry" },
      { name: "Carrot", qtyPerServing: "1", category: "produce" },
      { name: "Onion", qtyPerServing: "½", category: "produce" },
      { name: "Cumin", qtyPerServing: "1 tsp", category: "pantry" },
      { name: "Vegetable stock", qtyPerServing: "500 ml", category: "pantry" },
      { name: "Lemon", qtyPerServing: "wedge", category: "produce" },
    ],
    steps: [
      "Soften onion and carrot in oil, add cumin.",
      "Add lentils and stock, simmer 20 min until soft.",
      "Blend roughly, finish with lemon juice.",
    ],
    calories: 420, protein: 22, carbs: 62, fats: 8,
    portions: { protein: "1 palm lentils", carbs: "1.5 fists lentils", veg: "1 handful", fats: "1 thumb oil" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },

  // ───────── NEW RECIPES — Cuisines ─────────

  // ITALIAN
  { id: "b6", name: "Ricotta Toast with Figs & Honey", mealType: "breakfast",
    imagePrompt: "ricotta toast figs honey on plate", prepMinutes: 8, effort: "nobrain", budget: "medium",
    tags: ["vegetarian", "italian"], contains: ["ricotta", "bread", "figs", "honey"],
    ingredients: [
      { name: "Sourdough", qtyPerServing: "2 slices", category: "grains" },
      { name: "Ricotta", qtyPerServing: "80 g", category: "dairy" },
      { name: "Fresh figs", qtyPerServing: "2", category: "produce" },
      { name: "Honey", qtyPerServing: "1 tsp", category: "pantry" },
    ],
    steps: ["Toast sourdough.", "Spread ricotta, top with sliced figs and honey."],
    calories: 360, protein: 14, carbs: 48, fats: 12,
    portions: { protein: "1 thumb ricotta", carbs: "2 slices bread", veg: "2 figs", fats: "drizzle honey" },
    warmth: "neutral", carbDensity: "medium", style: "balanced",
  },
  { id: "l6", name: "Pesto Penne with Spinach & Pine Nuts", mealType: "lunch",
    imagePrompt: "pesto penne pasta spinach pine nuts bowl", prepMinutes: 15, effort: "simple", budget: "medium",
    tags: ["vegetarian", "italian"], contains: ["penne", "pesto", "spinach", "pine nuts", "pasta"],
    ingredients: [
      { name: "Penne", qtyPerServing: "80 g", category: "grains" },
      { name: "Pesto", qtyPerServing: "2 tbsp", category: "pantry" },
      { name: "Spinach", qtyPerServing: "60 g", category: "produce" },
      { name: "Pine nuts", qtyPerServing: "10 g", category: "pantry" },
      { name: "Parmesan", qtyPerServing: "15 g", category: "dairy" },
    ],
    steps: ["Cook penne al dente.", "Toss with pesto off heat, wilt spinach.", "Top with pine nuts and parmesan."],
    calories: 520, protein: 18, carbs: 64, fats: 22,
    portions: { protein: "1 thumb cheese", carbs: "2 fists penne", veg: "2 fists spinach", fats: "1 thumb pesto" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },
  { id: "d7", name: "Lemon Chicken Risotto", mealType: "dinner",
    imagePrompt: "creamy lemon chicken risotto in bowl", prepMinutes: 30, effort: "proper", budget: "medium",
    tags: ["italian"], contains: ["chicken", "risotto", "rice", "lemon", "parmesan"],
    ingredients: [
      { name: "Chicken breast", qtyPerServing: "120 g", category: "protein" },
      { name: "Arborio rice", qtyPerServing: "80 g", category: "grains" },
      { name: "Lemon", qtyPerServing: "1", category: "produce" },
      { name: "Parmesan", qtyPerServing: "20 g", category: "dairy" },
      { name: "Chicken stock", qtyPerServing: "400 ml", category: "pantry" },
      { name: "Butter", qtyPerServing: "10 g", category: "dairy" },
    ],
    steps: ["Pan-fry chicken, slice.", "Toast rice, add stock ladle by ladle.", "Finish with lemon zest, parmesan and butter."],
    calories: 560, protein: 38, carbs: 68, fats: 14,
    portions: { protein: "1 palm chicken", carbs: "2 fists rice", veg: "lemon", fats: "1 thumb parmesan" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },
  { id: "d8", name: "Spaghetti Carbonara", mealType: "dinner",
    imagePrompt: "spaghetti carbonara with egg and guanciale", prepMinutes: 20, effort: "simple", budget: "medium",
    tags: ["italian"], contains: ["spaghetti", "egg", "bacon", "parmesan", "pasta"],
    ingredients: [
      { name: "Spaghetti", qtyPerServing: "80 g", category: "grains" },
      { name: "Bacon or pancetta", qtyPerServing: "40 g", category: "protein" },
      { name: "Eggs", qtyPerServing: "2", category: "protein" },
      { name: "Parmesan", qtyPerServing: "25 g", category: "dairy" },
      { name: "Black pepper", qtyPerServing: "generous", category: "pantry" },
    ],
    steps: ["Cook pasta. Fry bacon until crisp.", "Mix eggs with parmesan.", "Toss hot pasta with bacon off-heat, then egg mixture. Pepper generously."],
    calories: 580, protein: 28, carbs: 62, fats: 24,
    portions: { protein: "1 palm bacon + eggs", carbs: "2 fists pasta", veg: "none", fats: "1 thumb parmesan" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },

  // MEXICAN
  { id: "l7", name: "Chicken Burrito Bowl", mealType: "lunch",
    imagePrompt: "chicken burrito bowl rice beans avocado lime", prepMinutes: 20, effort: "simple", budget: "low",
    tags: ["mexican", "gluten-free"], contains: ["chicken", "rice", "beans", "avocado", "lime"],
    ingredients: [
      { name: "Chicken thigh", qtyPerServing: "120 g", category: "protein" },
      { name: "Rice", qtyPerServing: "70 g", category: "grains" },
      { name: "Black beans", qtyPerServing: "80 g", category: "pantry" },
      { name: "Avocado", qtyPerServing: "½", category: "produce" },
      { name: "Lime", qtyPerServing: "½", category: "produce" },
      { name: "Cumin", qtyPerServing: "1 tsp", category: "pantry" },
    ],
    steps: ["Cook rice. Season chicken with cumin, pan-fry.", "Warm beans. Assemble bowl with sliced avocado and lime."],
    calories: 560, protein: 36, carbs: 58, fats: 20,
    portions: { protein: "1 palm chicken", carbs: "1.5 fists rice + beans", veg: "½ avocado", fats: "½ avocado" },
    warmth: "neutral", carbDensity: "high", style: "balanced",
  },
  { id: "d9", name: "Lime Chicken Tacos", mealType: "dinner",
    imagePrompt: "soft tacos lime chicken fresh salsa", prepMinutes: 18, effort: "simple", budget: "low",
    tags: ["mexican"], contains: ["chicken", "tortilla", "lime", "onion", "coriander"],
    ingredients: [
      { name: "Chicken breast", qtyPerServing: "120 g", category: "protein" },
      { name: "Soft tortillas", qtyPerServing: "2", category: "grains" },
      { name: "Lime", qtyPerServing: "1", category: "produce" },
      { name: "Red onion", qtyPerServing: "¼", category: "produce" },
      { name: "Coriander", qtyPerServing: "handful", category: "produce" },
      { name: "Greek yogurt", qtyPerServing: "2 tbsp", category: "dairy" },
    ],
    steps: ["Marinate chicken in lime juice and spices, grill or pan-fry.", "Dice onion, chop coriander.", "Assemble tacos with yogurt drizzle."],
    calories: 440, protein: 34, carbs: 40, fats: 14,
    portions: { protein: "1 palm chicken", carbs: "2 tortillas", veg: "1 fist toppings", fats: "1 thumb yogurt" },
    warmth: "neutral", carbDensity: "medium", style: "balanced",
  },
  { id: "b7", name: "Huevos Rancheros", mealType: "breakfast",
    imagePrompt: "huevos rancheros eggs tortilla salsa beans", prepMinutes: 15, effort: "simple", budget: "low",
    tags: ["vegetarian", "mexican"], contains: ["egg", "tortilla", "beans", "tomato"],
    ingredients: [
      { name: "Eggs", qtyPerServing: "2", category: "protein" },
      { name: "Corn tortilla", qtyPerServing: "1", category: "grains" },
      { name: "Black beans", qtyPerServing: "80 g", category: "pantry" },
      { name: "Tinned tomatoes", qtyPerServing: "100 g", category: "pantry" },
      { name: "Cumin", qtyPerServing: "½ tsp", category: "pantry" },
    ],
    steps: ["Warm beans with tomatoes and cumin.", "Fry eggs. Crisp tortilla.", "Stack tortilla, beans, eggs."],
    calories: 380, protein: 22, carbs: 38, fats: 16,
    portions: { protein: "2 eggs", carbs: "1 tortilla + beans", veg: "tomato sauce", fats: "cooking oil" },
    warmth: "warm", carbDensity: "medium", style: "comfort",
  },

  // ASIAN
  { id: "l8", name: "Teriyaki Salmon Rice Bowl", mealType: "lunch",
    imagePrompt: "teriyaki salmon rice bowl edamame cucumber", prepMinutes: 20, effort: "simple", budget: "high",
    tags: ["asian", "gluten-free", "pescatarian"], contains: ["salmon", "rice", "soy", "edamame"],
    ingredients: [
      { name: "Salmon fillet", qtyPerServing: "120 g", category: "protein" },
      { name: "Rice", qtyPerServing: "70 g", category: "grains" },
      { name: "Soy sauce", qtyPerServing: "1 tbsp", category: "pantry" },
      { name: "Honey", qtyPerServing: "1 tsp", category: "pantry" },
      { name: "Edamame", qtyPerServing: "50 g", category: "protein" },
      { name: "Cucumber", qtyPerServing: "¼", category: "produce" },
    ],
    steps: ["Cook rice. Glaze salmon with soy and honey, pan-fry.", "Slice cucumber, warm edamame.", "Assemble bowl."],
    calories: 540, protein: 36, carbs: 56, fats: 18,
    portions: { protein: "1 palm salmon", carbs: "1.5 fists rice", veg: "edamame + cucumber", fats: "in salmon" },
    warmth: "neutral", carbDensity: "high", style: "clean",
  },
  { id: "d10", name: "Chicken Pad Thai", mealType: "dinner",
    imagePrompt: "chicken pad thai noodles peanuts lime", prepMinutes: 22, effort: "simple", budget: "medium",
    tags: ["asian"], contains: ["chicken", "rice noodles", "peanuts", "egg", "lime"],
    ingredients: [
      { name: "Chicken breast", qtyPerServing: "100 g", category: "protein" },
      { name: "Rice noodles", qtyPerServing: "80 g", category: "grains" },
      { name: "Egg", qtyPerServing: "1", category: "protein" },
      { name: "Bean sprouts", qtyPerServing: "50 g", category: "produce" },
      { name: "Peanuts", qtyPerServing: "15 g", category: "pantry" },
      { name: "Fish sauce", qtyPerServing: "1 tbsp", category: "pantry" },
      { name: "Lime", qtyPerServing: "½", category: "produce" },
    ],
    steps: ["Soak noodles. Stir-fry chicken, push aside, scramble egg.", "Add noodles, fish sauce, bean sprouts. Toss.", "Top with peanuts and lime."],
    calories: 510, protein: 32, carbs: 60, fats: 16,
    portions: { protein: "1 palm chicken + egg", carbs: "2 fists noodles", veg: "1 fist sprouts", fats: "1 thumb peanuts" },
    warmth: "warm", carbDensity: "high", style: "balanced",
  },
  { id: "l9", name: "Miso Soup with Tofu & Greens", mealType: "lunch",
    imagePrompt: "japanese miso soup tofu seaweed scallions", prepMinutes: 10, effort: "nobrain", budget: "low",
    tags: ["vegan", "asian", "gluten-free"], contains: ["tofu", "miso", "seaweed", "scallion"],
    ingredients: [
      { name: "White miso paste", qtyPerServing: "2 tbsp", category: "pantry" },
      { name: "Silken tofu", qtyPerServing: "100 g", category: "protein" },
      { name: "Dried seaweed", qtyPerServing: "5 g", category: "pantry" },
      { name: "Scallions", qtyPerServing: "2", category: "produce" },
      { name: "Spinach", qtyPerServing: "30 g", category: "produce" },
    ],
    steps: ["Bring water to a simmer, dissolve miso.", "Add cubed tofu, seaweed, spinach.", "Top with sliced scallions."],
    calories: 180, protein: 14, carbs: 12, fats: 8,
    portions: { protein: "1 palm tofu", carbs: "broth", veg: "1 fist greens", fats: "in miso" },
    warmth: "warm", carbDensity: "low", style: "clean",
  },
  { id: "d11", name: "Egg Fried Rice with Vegetables", mealType: "dinner",
    imagePrompt: "vegetable egg fried rice wok", prepMinutes: 12, effort: "nobrain", budget: "low",
    tags: ["vegetarian", "asian"], contains: ["rice", "egg", "peas", "carrot", "soy"],
    ingredients: [
      { name: "Cooked rice", qtyPerServing: "150 g", category: "grains" },
      { name: "Eggs", qtyPerServing: "2", category: "protein" },
      { name: "Frozen peas", qtyPerServing: "50 g", category: "produce" },
      { name: "Carrot", qtyPerServing: "1 small", category: "produce" },
      { name: "Soy sauce", qtyPerServing: "1 tbsp", category: "pantry" },
      { name: "Sesame oil", qtyPerServing: "1 tsp", category: "pantry" },
    ],
    steps: ["Scramble eggs in hot wok, set aside.", "Stir-fry diced carrot and peas.", "Add cold rice, soy, sesame oil, eggs. Toss until hot."],
    calories: 430, protein: 18, carbs: 58, fats: 14,
    portions: { protein: "2 eggs", carbs: "2 fists rice", veg: "1 fist veg", fats: "1 tsp oil" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },

  // MIDDLE EASTERN
  { id: "b8", name: "Shakshuka", mealType: "breakfast",
    imagePrompt: "shakshuka eggs tomato sauce skillet herbs", prepMinutes: 18, effort: "simple", budget: "low",
    tags: ["vegetarian", "gluten-free", "middleeastern"], contains: ["egg", "tomato", "pepper", "cumin", "onion"],
    ingredients: [
      { name: "Eggs", qtyPerServing: "2", category: "protein" },
      { name: "Tinned tomatoes", qtyPerServing: "200 g", category: "pantry" },
      { name: "Red pepper", qtyPerServing: "½", category: "produce" },
      { name: "Onion", qtyPerServing: "½", category: "produce" },
      { name: "Cumin", qtyPerServing: "1 tsp", category: "pantry" },
      { name: "Bread", qtyPerServing: "1 slice", category: "grains" },
    ],
    steps: ["Soften onion and pepper, add cumin and tomatoes.", "Simmer 8 min, make wells, crack in eggs.", "Cover and cook until set. Serve with bread."],
    calories: 340, protein: 18, carbs: 30, fats: 16,
    portions: { protein: "2 eggs", carbs: "1 slice bread", veg: "2 fists sauce", fats: "cooking oil" },
    warmth: "warm", carbDensity: "medium", style: "balanced",
  },
  { id: "l10", name: "Chicken Shawarma Wrap", mealType: "lunch",
    imagePrompt: "chicken shawarma wrap with pickles and tahini", prepMinutes: 18, effort: "simple", budget: "low",
    tags: ["middleeastern"], contains: ["chicken", "wrap", "tahini", "lettuce", "tomato"],
    ingredients: [
      { name: "Chicken thigh", qtyPerServing: "120 g", category: "protein" },
      { name: "Flatbread wrap", qtyPerServing: "1", category: "grains" },
      { name: "Tahini", qtyPerServing: "1 tbsp", category: "pantry" },
      { name: "Lettuce", qtyPerServing: "handful", category: "produce" },
      { name: "Tomato", qtyPerServing: "½", category: "produce" },
      { name: "Shawarma spice mix", qtyPerServing: "1 tsp", category: "pantry" },
    ],
    steps: ["Season chicken with shawarma spice, pan-fry until golden.", "Slice thinly. Warm wrap.", "Fill with chicken, lettuce, tomato, drizzle tahini."],
    calories: 480, protein: 34, carbs: 38, fats: 20,
    portions: { protein: "1 palm chicken", carbs: "1 wrap", veg: "1 fist salad", fats: "1 thumb tahini" },
    warmth: "warm", carbDensity: "medium", style: "balanced",
  },
  { id: "d12", name: "Spiced Chickpea & Spinach Stew", mealType: "dinner",
    imagePrompt: "chickpea spinach stew cumin warm bowl", prepMinutes: 20, effort: "simple", budget: "low",
    tags: ["vegan", "gluten-free", "middleeastern"], contains: ["chickpeas", "spinach", "tomato", "cumin", "garlic"],
    ingredients: [
      { name: "Chickpeas (tinned)", qtyPerServing: "200 g", category: "pantry" },
      { name: "Spinach", qtyPerServing: "80 g", category: "produce" },
      { name: "Tinned tomatoes", qtyPerServing: "150 g", category: "pantry" },
      { name: "Garlic", qtyPerServing: "2 cloves", category: "produce" },
      { name: "Cumin", qtyPerServing: "1 tsp", category: "pantry" },
      { name: "Olive oil", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: ["Sauté garlic in oil, add cumin.", "Add tomatoes and chickpeas, simmer 12 min.", "Wilt spinach, season to taste."],
    calories: 380, protein: 18, carbs: 48, fats: 14,
    portions: { protein: "1 fist chickpeas", carbs: "1 fist chickpeas", veg: "2 fists spinach", fats: "1 thumb oil" },
    warmth: "warm", carbDensity: "medium", style: "clean",
  },

  // INDIAN
  { id: "d13", name: "Red Lentil Dhal", mealType: "dinner",
    imagePrompt: "creamy red lentil dhal with rice and coriander", prepMinutes: 25, effort: "simple", budget: "low",
    tags: ["vegan", "gluten-free", "indian"], contains: ["lentils", "coconut milk", "turmeric", "ginger", "garlic"],
    ingredients: [
      { name: "Red lentils", qtyPerServing: "80 g", category: "grains" },
      { name: "Coconut milk", qtyPerServing: "100 ml", category: "pantry" },
      { name: "Turmeric", qtyPerServing: "1 tsp", category: "pantry" },
      { name: "Ginger", qtyPerServing: "1 cm", category: "produce" },
      { name: "Garlic", qtyPerServing: "2 cloves", category: "produce" },
      { name: "Rice", qtyPerServing: "70 g", category: "grains" },
    ],
    steps: ["Sauté garlic and ginger, add turmeric.", "Add lentils and water, simmer 18 min.", "Stir in coconut milk. Serve over rice."],
    calories: 480, protein: 20, carbs: 68, fats: 14,
    portions: { protein: "1 fist lentils", carbs: "2 fists lentils + rice", veg: "in sauce", fats: "coconut milk" },
    warmth: "warm", carbDensity: "high", style: "clean",
  },
  { id: "l11", name: "Spiced Chicken Tikka Bowl", mealType: "lunch",
    imagePrompt: "chicken tikka bowl with rice and raita", prepMinutes: 22, effort: "simple", budget: "medium",
    tags: ["indian", "gluten-free"], contains: ["chicken", "yogurt", "rice", "spices", "cucumber"],
    ingredients: [
      { name: "Chicken breast", qtyPerServing: "120 g", category: "protein" },
      { name: "Greek yogurt", qtyPerServing: "60 g", category: "dairy" },
      { name: "Tikka spice paste", qtyPerServing: "1 tbsp", category: "pantry" },
      { name: "Rice", qtyPerServing: "70 g", category: "grains" },
      { name: "Cucumber", qtyPerServing: "¼", category: "produce" },
      { name: "Mint", qtyPerServing: "small bunch", category: "produce" },
    ],
    steps: ["Marinate chicken in yogurt and tikka paste 10 min.", "Grill or pan-fry until charred.", "Serve with rice and cucumber-mint raita."],
    calories: 490, protein: 38, carbs: 52, fats: 12,
    portions: { protein: "1 palm chicken", carbs: "1.5 fists rice", veg: "raita", fats: "in marinade" },
    warmth: "warm", carbDensity: "high", style: "balanced",
  },

  // FRENCH
  { id: "l12", name: "Croque-Monsieur", mealType: "lunch",
    imagePrompt: "croque monsieur grilled ham cheese sandwich", prepMinutes: 12, effort: "simple", budget: "low",
    tags: ["french"], contains: ["bread", "ham", "cheese", "butter", "milk"],
    ingredients: [
      { name: "Bread", qtyPerServing: "2 slices", category: "grains" },
      { name: "Ham", qtyPerServing: "60 g", category: "protein" },
      { name: "Gruyère", qtyPerServing: "40 g", category: "dairy" },
      { name: "Butter", qtyPerServing: "10 g", category: "dairy" },
      { name: "Dijon mustard", qtyPerServing: "1 tsp", category: "pantry" },
    ],
    steps: ["Spread mustard on bread, layer ham and cheese.", "Butter outside, grill in pan until golden and melted."],
    calories: 480, protein: 26, carbs: 36, fats: 26,
    portions: { protein: "1 palm ham + cheese", carbs: "2 slices bread", veg: "none", fats: "1 thumb butter" },
    warmth: "warm", carbDensity: "medium", style: "comfort",
  },
  { id: "d14", name: "Ratatouille with Crusty Bread", mealType: "dinner",
    imagePrompt: "provencal ratatouille vegetables in dish", prepMinutes: 35, effort: "proper", budget: "low",
    tags: ["vegan", "french"], contains: ["courgette", "aubergine", "pepper", "tomato", "onion"],
    ingredients: [
      { name: "Courgette", qtyPerServing: "1 small", category: "produce" },
      { name: "Aubergine", qtyPerServing: "½", category: "produce" },
      { name: "Red pepper", qtyPerServing: "1", category: "produce" },
      { name: "Tinned tomatoes", qtyPerServing: "200 g", category: "pantry" },
      { name: "Onion", qtyPerServing: "1", category: "produce" },
      { name: "Olive oil", qtyPerServing: "2 tbsp", category: "pantry" },
      { name: "Crusty bread", qtyPerServing: "2 slices", category: "grains" },
    ],
    steps: ["Dice all veg, sauté onion and aubergine first.", "Add pepper, courgette, then tomatoes.", "Simmer 20 min. Serve with bread."],
    calories: 340, protein: 8, carbs: 44, fats: 16,
    portions: { protein: "veg protein", carbs: "2 slices bread", veg: "3 fists veg", fats: "1 thumb oil" },
    warmth: "warm", carbDensity: "medium", style: "clean",
  },
  { id: "b9", name: "French Toast with Berries", mealType: "breakfast",
    imagePrompt: "french toast berries maple syrup plate", prepMinutes: 12, effort: "simple", budget: "low",
    tags: ["vegetarian", "french"], contains: ["bread", "egg", "milk", "berries", "maple syrup"],
    ingredients: [
      { name: "Bread", qtyPerServing: "2 thick slices", category: "grains" },
      { name: "Egg", qtyPerServing: "1", category: "protein" },
      { name: "Milk", qtyPerServing: "50 ml", category: "dairy" },
      { name: "Mixed berries", qtyPerServing: "80 g", category: "produce" },
      { name: "Maple syrup", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: ["Whisk egg with milk and cinnamon.", "Dip bread, fry in butter until golden.", "Top with berries and maple drizzle."],
    calories: 400, protein: 14, carbs: 52, fats: 16,
    portions: { protein: "1 egg", carbs: "2 slices bread", veg: "1 fist berries", fats: "cooking butter" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },

  // AMERICAN COMFORT
  { id: "d15", name: "Mac & Cheese", mealType: "dinner",
    imagePrompt: "creamy mac and cheese baked golden top", prepMinutes: 22, effort: "simple", budget: "low",
    tags: ["vegetarian", "american"], contains: ["macaroni", "cheddar", "milk", "butter", "pasta"],
    ingredients: [
      { name: "Macaroni", qtyPerServing: "80 g", category: "grains" },
      { name: "Cheddar", qtyPerServing: "50 g", category: "dairy" },
      { name: "Milk", qtyPerServing: "100 ml", category: "dairy" },
      { name: "Butter", qtyPerServing: "10 g", category: "dairy" },
      { name: "Flour", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: ["Cook macaroni. Make roux with butter and flour.", "Add milk gradually, then cheese until melted.", "Combine with pasta."],
    calories: 540, protein: 22, carbs: 60, fats: 24,
    portions: { protein: "cheese", carbs: "2 fists pasta", veg: "none", fats: "1 thumb butter + cheese" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },
  { id: "b10", name: "Banana Pancakes", mealType: "breakfast",
    imagePrompt: "fluffy banana pancakes stack maple syrup", prepMinutes: 15, effort: "simple", budget: "low",
    tags: ["vegetarian", "american"], contains: ["banana", "egg", "flour", "milk"],
    ingredients: [
      { name: "Banana", qtyPerServing: "1", category: "produce" },
      { name: "Egg", qtyPerServing: "1", category: "protein" },
      { name: "Flour", qtyPerServing: "50 g", category: "grains" },
      { name: "Milk", qtyPerServing: "60 ml", category: "dairy" },
      { name: "Maple syrup", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: ["Mash banana, mix with egg, flour, milk.", "Cook small pancakes in a non-stick pan.", "Stack and drizzle with maple syrup."],
    calories: 340, protein: 12, carbs: 56, fats: 8,
    portions: { protein: "1 egg", carbs: "1 banana + flour", veg: "banana", fats: "cooking oil" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },

  // MEDITERRANEAN
  { id: "l13", name: "Greek Salad with Grilled Halloumi", mealType: "lunch",
    imagePrompt: "greek salad halloumi cheese cucumber tomato olives", prepMinutes: 10, effort: "nobrain", budget: "medium",
    tags: ["vegetarian", "gluten-free", "mediterranean"], contains: ["halloumi", "cucumber", "tomato", "olives", "red onion"],
    ingredients: [
      { name: "Halloumi", qtyPerServing: "80 g", category: "dairy" },
      { name: "Cucumber", qtyPerServing: "½", category: "produce" },
      { name: "Tomato", qtyPerServing: "1", category: "produce" },
      { name: "Kalamata olives", qtyPerServing: "6", category: "pantry" },
      { name: "Red onion", qtyPerServing: "¼", category: "produce" },
      { name: "Olive oil", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: ["Grill halloumi slices until golden.", "Chop cucumber, tomato, onion. Toss with olives and oil.", "Top with halloumi."],
    calories: 380, protein: 22, carbs: 12, fats: 28,
    portions: { protein: "1 palm halloumi", carbs: "minimal", veg: "2 fists salad", fats: "olives + oil" },
    warmth: "cool", carbDensity: "low", style: "clean",
  },

  // QUICK RECIPES (<10 min)
  { id: "b11", name: "Overnight Chia Pudding", mealType: "breakfast",
    imagePrompt: "chia seed pudding berries coconut glass jar", prepMinutes: 5, effort: "nobrain", budget: "medium",
    tags: ["vegan", "gluten-free"], contains: ["chia seeds", "coconut milk", "berries", "maple"],
    ingredients: [
      { name: "Chia seeds", qtyPerServing: "30 g", category: "pantry" },
      { name: "Coconut milk", qtyPerServing: "200 ml", category: "pantry" },
      { name: "Mixed berries", qtyPerServing: "60 g", category: "produce" },
      { name: "Maple syrup", qtyPerServing: "1 tsp", category: "pantry" },
    ],
    steps: ["Mix chia with coconut milk and maple. Stir well.", "Refrigerate overnight.", "Top with berries before eating."],
    calories: 320, protein: 8, carbs: 28, fats: 20,
    portions: { protein: "chia", carbs: "chia + berries", veg: "berries", fats: "coconut milk" },
    warmth: "cool", carbDensity: "medium", style: "clean",
  },
  { id: "l14", name: "Hummus & Veggie Wrap", mealType: "lunch",
    imagePrompt: "hummus vegetable wrap spinach carrot", prepMinutes: 5, effort: "nobrain", budget: "low",
    tags: ["vegan", "mediterranean"], contains: ["hummus", "wrap", "spinach", "carrot", "cucumber"],
    ingredients: [
      { name: "Tortilla wrap", qtyPerServing: "1", category: "grains" },
      { name: "Hummus", qtyPerServing: "3 tbsp", category: "pantry" },
      { name: "Spinach", qtyPerServing: "handful", category: "produce" },
      { name: "Carrot", qtyPerServing: "1 small", category: "produce" },
      { name: "Cucumber", qtyPerServing: "¼", category: "produce" },
    ],
    steps: ["Spread hummus on wrap.", "Layer spinach, grated carrot, sliced cucumber.", "Roll tightly and cut in half."],
    calories: 340, protein: 12, carbs: 42, fats: 14,
    portions: { protein: "hummus", carbs: "1 wrap", veg: "2 fists veg", fats: "in hummus" },
    warmth: "cool", carbDensity: "medium", style: "clean",
  },
];

