import type { Recipe } from "./types";

// V1 mock recipe DB. The selection engine in meal-planner.ts filters and ranks these
// using the user's profile + daily context. Designed to be replaced by a server-side
// AI call (see meal-planner.ts) without changing consumers.
export const RECIPES: Recipe[] = [
  // ───────── Breakfasts ─────────
  {
    id: "b1",
    name: "Apple & Walnut Overnight Oats",
    mealType: "breakfast",
    imagePrompt: "overnight oats in a glass jar with apple and walnuts, soft morning light",
    prepMinutes: 5,
    effort: "nobrain",
    budget: "low",
    tags: ["vegetarian"],
    contains: ["oats", "apple", "walnut", "yogurt", "milk"],
    ingredients: [
      { name: "Rolled oats", qtyPerServing: "50 g", category: "grains" },
      { name: "Plant or dairy milk", qtyPerServing: "180 ml", category: "dairy" },
      { name: "Greek yogurt", qtyPerServing: "60 g", category: "dairy" },
      { name: "Apple", qtyPerServing: "½", category: "produce" },
      { name: "Walnuts", qtyPerServing: "15 g", category: "pantry" },
      { name: "Cinnamon", qtyPerServing: "pinch", category: "pantry" },
    ],
    steps: [
      "Mix oats, milk and yogurt in a jar. Stir well.",
      "Top with grated apple, walnuts and cinnamon.",
      "Refrigerate overnight, or eat after 10 minutes for a softer texture.",
    ],
    calories: 380, protein: 14, carbs: 52, fats: 12,
    portions: { protein: "1 thumb of yogurt", carbs: "1 fist of oats", veg: "½ apple", fats: "1 thumb of nuts" },
    warmth: "neutral", carbDensity: "medium", style: "clean",
  },
  {
    id: "b2",
    name: "Soft Scramble on Sourdough",
    mealType: "breakfast",
    imagePrompt: "soft buttery scrambled eggs on toasted sourdough with chives",
    prepMinutes: 10,
    effort: "simple",
    budget: "low",
    tags: ["vegetarian"],
    contains: ["egg", "butter", "bread", "sourdough"],
    ingredients: [
      { name: "Eggs", qtyPerServing: "2", category: "protein" },
      { name: "Butter", qtyPerServing: "10 g", category: "dairy" },
      { name: "Sourdough", qtyPerServing: "1 slice", category: "grains" },
      { name: "Chives", qtyPerServing: "to taste", category: "produce" },
    ],
    steps: [
      "Whisk eggs with a pinch of salt.",
      "Melt butter in a non-stick pan over low heat, add eggs and stir slowly.",
      "Remove while still glossy. Pile onto toasted sourdough, top with chives.",
    ],
    calories: 420, protein: 22, carbs: 28, fats: 24,
    portions: { protein: "1 palm of eggs", carbs: "1 fist of bread", veg: "small handful herbs", fats: "1 thumb of butter" },
    warmth: "warm", carbDensity: "medium", style: "comfort",
  },
  {
    id: "b3",
    name: "Berry Protein Smoothie",
    mealType: "breakfast",
    imagePrompt: "purple berry smoothie in a tall glass with chia seeds on top",
    prepMinutes: 5,
    effort: "nobrain",
    budget: "medium",
    tags: ["vegetarian", "gluten-free"],
    contains: ["berries", "banana", "yogurt", "milk", "chia"],
    ingredients: [
      { name: "Frozen berries", qtyPerServing: "120 g", category: "produce" },
      { name: "Banana", qtyPerServing: "½", category: "produce" },
      { name: "Greek yogurt", qtyPerServing: "150 g", category: "dairy" },
      { name: "Milk of choice", qtyPerServing: "150 ml", category: "dairy" },
      { name: "Chia seeds", qtyPerServing: "1 tsp", category: "pantry" },
    ],
    steps: [
      "Blend everything until smooth and creamy.",
      "Pour into a glass, top with a few extra berries.",
    ],
    calories: 320, protein: 24, carbs: 38, fats: 7,
    portions: { protein: "1 palm of yogurt", carbs: "1 fist of fruit", veg: "—", fats: "1 thumb of seeds" },
    warmth: "cool", carbDensity: "medium", style: "clean",
  },
  {
    id: "b4",
    name: "Savoury Spinach & Feta Omelette",
    mealType: "breakfast",
    imagePrompt: "fluffy omelette folded over spinach and feta on a ceramic plate",
    prepMinutes: 10,
    effort: "simple",
    budget: "low",
    tags: ["vegetarian", "gluten-free"],
    contains: ["egg", "spinach", "feta", "dairy"],
    ingredients: [
      { name: "Eggs", qtyPerServing: "3", category: "protein" },
      { name: "Spinach", qtyPerServing: "large handful", category: "produce" },
      { name: "Feta", qtyPerServing: "30 g", category: "dairy" },
      { name: "Olive oil", qtyPerServing: "1 tsp", category: "pantry" },
    ],
    steps: [
      "Wilt spinach in a hot oiled pan, set aside.",
      "Pour beaten eggs into the pan, swirl, and let set on low heat.",
      "Top with spinach and feta, fold and slide onto a plate.",
    ],
    calories: 380, protein: 28, carbs: 4, fats: 28,
    portions: { protein: "1.5 palms of eggs", carbs: "—", veg: "2 handfuls spinach", fats: "1 thumb feta" },
    warmth: "warm", carbDensity: "low", style: "balanced",
  },
  {
    id: "b5",
    name: "Banana Nut Porridge",
    mealType: "breakfast",
    imagePrompt: "warm porridge bowl topped with banana slices, almonds and honey",
    prepMinutes: 12,
    effort: "simple",
    budget: "low",
    tags: ["vegetarian"],
    contains: ["oats", "banana", "almond", "milk"],
    ingredients: [
      { name: "Rolled oats", qtyPerServing: "60 g", category: "grains" },
      { name: "Milk of choice", qtyPerServing: "250 ml", category: "dairy" },
      { name: "Banana", qtyPerServing: "1", category: "produce" },
      { name: "Almonds", qtyPerServing: "15 g", category: "pantry" },
      { name: "Honey or maple", qtyPerServing: "1 tsp", category: "pantry" },
    ],
    steps: [
      "Simmer oats with milk on low for 5–7 minutes until creamy.",
      "Pour into a bowl and top with sliced banana, almonds and a drizzle of honey.",
    ],
    calories: 460, protein: 14, carbs: 72, fats: 14,
    portions: { protein: "1 thumb of nuts", carbs: "1.5 fists of oats", veg: "—", fats: "1 thumb of nuts" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },

  // ───────── Lunches ─────────
  {
    id: "l1",
    name: "Lemon Tahini Grain Bowl",
    mealType: "lunch",
    imagePrompt: "vibrant grain bowl with quinoa, roasted chickpeas, greens and lemon tahini",
    prepMinutes: 20,
    effort: "simple",
    budget: "medium",
    tags: ["vegetarian", "vegan", "nut-free"],
    contains: ["quinoa", "chickpeas", "tahini", "greens", "lemon"],
    ingredients: [
      { name: "Quinoa", qtyPerServing: "70 g dry", category: "grains" },
      { name: "Chickpeas (cooked)", qtyPerServing: "150 g", category: "protein" },
      { name: "Mixed greens", qtyPerServing: "2 handfuls", category: "produce" },
      { name: "Tahini", qtyPerServing: "1 tbsp", category: "pantry" },
      { name: "Lemon", qtyPerServing: "½", category: "produce" },
      { name: "Olive oil", qtyPerServing: "1 tsp", category: "pantry" },
    ],
    steps: [
      "Cook quinoa in salted water until fluffy. Drain.",
      "Roast chickpeas with olive oil for 12 min at 220°C until crisp.",
      "Whisk tahini with lemon juice and warm water to a pourable sauce.",
      "Build the bowl, drizzle with sauce.",
    ],
    calories: 540, protein: 22, carbs: 70, fats: 18,
    portions: { protein: "1 palm chickpeas", carbs: "1 fist quinoa", veg: "2 handfuls greens", fats: "1 thumb tahini" },
    warmth: "cool", carbDensity: "high", style: "clean",
  },
  {
    id: "l2",
    name: "Chicken & Avocado Wrap",
    mealType: "lunch",
    imagePrompt: "chicken wrap with avocado and lettuce cut in half on a wooden board",
    prepMinutes: 15,
    effort: "simple",
    budget: "medium",
    tags: [],
    contains: ["chicken", "avocado", "wrap", "tortilla", "yogurt"],
    ingredients: [
      { name: "Chicken breast", qtyPerServing: "120 g", category: "protein" },
      { name: "Wholewheat wrap", qtyPerServing: "1", category: "grains" },
      { name: "Avocado", qtyPerServing: "½", category: "produce" },
      { name: "Lettuce", qtyPerServing: "small handful", category: "produce" },
      { name: "Greek yogurt", qtyPerServing: "2 tbsp", category: "dairy" },
    ],
    steps: [
      "Sear seasoned chicken 4 min per side, rest, then slice.",
      "Spread yogurt across the wrap, layer lettuce, avocado, chicken.",
      "Roll tightly and slice in half.",
    ],
    calories: 520, protein: 38, carbs: 38, fats: 22,
    portions: { protein: "1 palm chicken", carbs: "1 fist wrap", veg: "1 handful lettuce", fats: "1 thumb avocado" },
    warmth: "neutral", carbDensity: "medium", style: "balanced",
  },
  {
    id: "l3",
    name: "Miso Salmon Rice Bowl",
    mealType: "lunch",
    imagePrompt: "glossy miso glazed salmon over rice with bok choy",
    prepMinutes: 25,
    effort: "proper",
    budget: "high",
    tags: ["pescatarian", "nut-free"],
    contains: ["salmon", "rice", "miso", "ginger", "bok choy"],
    ingredients: [
      { name: "Salmon fillet", qtyPerServing: "140 g", category: "protein" },
      { name: "Jasmine rice", qtyPerServing: "70 g dry", category: "grains" },
      { name: "Bok choy", qtyPerServing: "2 small heads", category: "produce" },
      { name: "White miso", qtyPerServing: "1 tbsp", category: "pantry" },
      { name: "Ginger", qtyPerServing: "thumb", category: "produce" },
    ],
    steps: [
      "Brush salmon with miso + grated ginger, bake at 200°C for 10 min.",
      "Cook rice. Steam bok choy until just tender.",
      "Plate rice, top with salmon and greens, spoon over pan juices.",
    ],
    calories: 620, protein: 40, carbs: 68, fats: 18,
    portions: { protein: "1 palm salmon", carbs: "1 fist rice", veg: "2 handfuls bok choy", fats: "1 thumb oils" },
    warmth: "warm", carbDensity: "high", style: "balanced",
  },
  {
    id: "l4",
    name: "10-Minute Tuna Bean Salad",
    mealType: "lunch",
    imagePrompt: "rustic tuna and white bean salad with parsley and lemon",
    prepMinutes: 10,
    effort: "nobrain",
    budget: "low",
    tags: ["pescatarian", "gluten-free", "nut-free"],
    contains: ["tuna", "beans", "lemon", "parsley", "olive"],
    ingredients: [
      { name: "Canned tuna", qtyPerServing: "1 tin (100 g)", category: "protein" },
      { name: "White beans (canned)", qtyPerServing: "150 g", category: "pantry" },
      { name: "Parsley", qtyPerServing: "small handful", category: "produce" },
      { name: "Lemon", qtyPerServing: "½", category: "produce" },
      { name: "Olive oil", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: [
      "Rinse beans, drain tuna.",
      "Toss everything with lemon juice, olive oil, salt and pepper.",
    ],
    calories: 420, protein: 34, carbs: 32, fats: 16,
    portions: { protein: "1 palm tuna", carbs: "1 fist beans", veg: "small handful herbs", fats: "1 thumb olive oil" },
    warmth: "cool", carbDensity: "medium", style: "clean",
  },
  {
    id: "l5",
    name: "Roasted Roots & Tahini Bowl",
    mealType: "lunch",
    imagePrompt: "roasted sweet potato and carrots over couscous with tahini and parsley",
    prepMinutes: 30,
    effort: "proper",
    budget: "low",
    tags: ["vegetarian", "vegan"],
    contains: ["sweet potato", "carrot", "couscous", "tahini", "chickpeas"],
    ingredients: [
      { name: "Sweet potato", qtyPerServing: "200 g", category: "produce" },
      { name: "Carrots", qtyPerServing: "2", category: "produce" },
      { name: "Couscous", qtyPerServing: "60 g dry", category: "grains" },
      { name: "Chickpeas", qtyPerServing: "100 g", category: "protein" },
      { name: "Tahini", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: [
      "Roast cubed roots and chickpeas with oil and cumin at 220°C for 25 min.",
      "Soak couscous in hot water for 5 min, fluff with a fork.",
      "Build the bowl and drizzle with thinned tahini.",
    ],
    calories: 560, protein: 18, carbs: 88, fats: 14,
    portions: { protein: "1 palm chickpeas", carbs: "1.5 fists roots+couscous", veg: "2 handfuls", fats: "1 thumb tahini" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },

  // ───────── Dinners ─────────
  {
    id: "d1",
    name: "Lemon Garlic Chicken & Greens",
    mealType: "dinner",
    imagePrompt: "pan seared chicken with lemon and sautéed greens on a ceramic plate",
    prepMinutes: 25,
    effort: "simple",
    budget: "medium",
    tags: ["gluten-free", "nut-free"],
    contains: ["chicken", "lemon", "garlic", "greens", "olive"],
    ingredients: [
      { name: "Chicken thighs", qtyPerServing: "180 g", category: "protein" },
      { name: "Garlic", qtyPerServing: "2 cloves", category: "produce" },
      { name: "Lemon", qtyPerServing: "½", category: "produce" },
      { name: "Greens (kale or chard)", qtyPerServing: "2 handfuls", category: "produce" },
      { name: "Olive oil", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: [
      "Sear chicken skin-side down for 6 min, flip, finish 5 min more.",
      "Remove chicken, sauté garlic and greens in the same pan.",
      "Return chicken, squeeze lemon over and serve.",
    ],
    calories: 480, protein: 42, carbs: 8, fats: 28,
    portions: { protein: "1.5 palms chicken", carbs: "—", veg: "2 handfuls greens", fats: "1 thumb olive oil" },
    warmth: "warm", carbDensity: "low", style: "balanced",
  },
  {
    id: "d2",
    name: "Roasted Tomato Recovery Pasta",
    mealType: "dinner",
    imagePrompt: "rustic pasta with slow roasted tomatoes, basil and parmesan",
    prepMinutes: 30,
    effort: "simple",
    budget: "low",
    tags: ["vegetarian"],
    contains: ["pasta", "tomato", "basil", "parmesan", "garlic"],
    ingredients: [
      { name: "Pasta", qtyPerServing: "100 g dry", category: "grains" },
      { name: "Cherry tomatoes", qtyPerServing: "250 g", category: "produce" },
      { name: "Garlic", qtyPerServing: "3 cloves", category: "produce" },
      { name: "Basil", qtyPerServing: "small handful", category: "produce" },
      { name: "Parmesan", qtyPerServing: "20 g", category: "dairy" },
      { name: "Olive oil", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: [
      "Roast tomatoes with garlic and oil at 200°C for 20 min.",
      "Cook pasta to al dente, keep a splash of water.",
      "Toss everything together, finish with basil and parmesan.",
    ],
    calories: 580, protein: 20, carbs: 92, fats: 14,
    portions: { protein: "1 thumb parmesan", carbs: "1.5 fists pasta", veg: "1 handful tomatoes", fats: "1 thumb oil" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },
  {
    id: "d3",
    name: "Chickpea Coconut Curry",
    mealType: "dinner",
    imagePrompt: "creamy chickpea curry with coconut milk and coriander over rice",
    prepMinutes: 25,
    effort: "simple",
    budget: "low",
    tags: ["vegetarian", "vegan", "gluten-free"],
    contains: ["chickpeas", "coconut", "tomato", "rice", "curry"],
    ingredients: [
      { name: "Chickpeas (cooked)", qtyPerServing: "180 g", category: "protein" },
      { name: "Coconut milk", qtyPerServing: "150 ml", category: "pantry" },
      { name: "Tinned tomatoes", qtyPerServing: "150 g", category: "pantry" },
      { name: "Onion", qtyPerServing: "½", category: "produce" },
      { name: "Curry powder", qtyPerServing: "1 tbsp", category: "pantry" },
      { name: "Rice", qtyPerServing: "70 g dry", category: "grains" },
    ],
    steps: [
      "Soften onion in oil, add curry powder and bloom 30 s.",
      "Add tomatoes and coconut milk, simmer 5 min.",
      "Stir in chickpeas, simmer 10 min. Serve with rice.",
    ],
    calories: 600, protein: 20, carbs: 82, fats: 20,
    portions: { protein: "1 palm chickpeas", carbs: "1 fist rice", veg: "1 handful onion+tomato", fats: "1 thumb coconut" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },
  {
    id: "d4",
    name: "Sheet-Pan Salmon & Greens",
    mealType: "dinner",
    imagePrompt: "sheet pan salmon with broccoli and lemon slices",
    prepMinutes: 20,
    effort: "simple",
    budget: "high",
    tags: ["pescatarian", "gluten-free", "nut-free"],
    contains: ["salmon", "broccoli", "lemon", "olive"],
    ingredients: [
      { name: "Salmon fillet", qtyPerServing: "150 g", category: "protein" },
      { name: "Broccoli", qtyPerServing: "200 g", category: "produce" },
      { name: "Lemon", qtyPerServing: "½", category: "produce" },
      { name: "Olive oil", qtyPerServing: "1 tbsp", category: "pantry" },
    ],
    steps: [
      "Toss broccoli with oil, roast at 220°C for 8 min.",
      "Push aside, lay salmon on the tray, roast 10 min more.",
      "Squeeze lemon over to finish.",
    ],
    calories: 460, protein: 38, carbs: 14, fats: 28,
    portions: { protein: "1 palm salmon", carbs: "—", veg: "2 handfuls broccoli", fats: "1 thumb olive oil" },
    warmth: "warm", carbDensity: "low", style: "clean",
  },
  {
    id: "d5",
    name: "Quick Stir-Fry Beef & Veg",
    mealType: "dinner",
    imagePrompt: "wok stir fry of beef strips with peppers and noodles",
    prepMinutes: 15,
    effort: "simple",
    budget: "medium",
    tags: [],
    contains: ["beef", "pepper", "noodle", "soy", "ginger"],
    ingredients: [
      { name: "Beef strips", qtyPerServing: "140 g", category: "protein" },
      { name: "Peppers", qtyPerServing: "1", category: "produce" },
      { name: "Egg noodles", qtyPerServing: "80 g dry", category: "grains" },
      { name: "Soy sauce", qtyPerServing: "1 tbsp", category: "pantry" },
      { name: "Ginger", qtyPerServing: "thumb", category: "produce" },
    ],
    steps: [
      "Cook noodles, drain.",
      "Sear beef in a hot wok 2 min, add peppers and ginger, toss 2 min.",
      "Add noodles and soy, toss to coat and serve.",
    ],
    calories: 560, protein: 38, carbs: 60, fats: 18,
    portions: { protein: "1 palm beef", carbs: "1 fist noodles", veg: "1 handful peppers", fats: "1 thumb oil" },
    warmth: "warm", carbDensity: "high", style: "balanced",
  },
  {
    id: "d6",
    name: "Lentil Soup with Cumin & Lemon",
    mealType: "dinner",
    imagePrompt: "warm red lentil soup with a swirl of olive oil and lemon",
    prepMinutes: 30,
    effort: "simple",
    budget: "low",
    tags: ["vegetarian", "vegan", "gluten-free"],
    contains: ["lentil", "carrot", "onion", "cumin", "lemon"],
    ingredients: [
      { name: "Red lentils", qtyPerServing: "80 g dry", category: "pantry" },
      { name: "Carrot", qtyPerServing: "1", category: "produce" },
      { name: "Onion", qtyPerServing: "½", category: "produce" },
      { name: "Cumin", qtyPerServing: "1 tsp", category: "pantry" },
      { name: "Vegetable stock", qtyPerServing: "500 ml", category: "pantry" },
      { name: "Lemon", qtyPerServing: "wedge", category: "produce" },
    ],
    steps: [
      "Soften onion and carrot in oil, add cumin.",
      "Add lentils and stock, simmer 20 min until soft.",
      "Blend roughly, finish with lemon juice.",
    ],
    calories: 420, protein: 22, carbs: 62, fats: 8,
    portions: { protein: "1 palm lentils", carbs: "1.5 fists lentils", veg: "1 handful", fats: "1 thumb oil" },
    warmth: "warm", carbDensity: "high", style: "comfort",
  },
];
